/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SitemapDotxmlRouteImport } from './app/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './app/robots[.]txt'
import { Route as RatingSpeedRunRouteImport } from './app/rating-speed-run'
import { Route as ContentCreatorsRouteImport } from './app/content-creators'
import { Route as ClubsRouteImport } from './app/clubs'
import { Route as ChessCameroonRouteImport } from './app/chess-cameroon'
import { Route as IndexRouteImport } from './app/index'
import { Route as TournamentsIndexRouteImport } from './app/tournaments.index'
import { Route as RatingSpeedRunIndexRouteImport } from './app/rating-speed-run.index'
import { Route as TournamentsPastOnlineRouteImport } from './app/tournaments.past-online'
import { Route as TournamentsIdRouteImport } from './app/tournaments.$id'
import { Route as RatingSpeedRunIdRouteImport } from './app/rating-speed-run.$id'
import { Route as ApiSubmitUsernameRouteImport } from './app/api/submit-username'
import { Route as ApiSubmitTournamentRouteImport } from './app/api/submit-tournament'
import { Route as ApiSubmitCreatorRouteImport } from './app/api/submit-creator'
import { Route as ApiSubmitClubRouteImport } from './app/api/submit-club'
import { Route as ApiRatingSpeedRunJoinRouteImport } from './app/api/rating-speed-run/join'
import { Route as ApiRatingSpeedRunCreateRouteImport } from './app/api/rating-speed-run/create'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingSpeedRunRoute = RatingSpeedRunRouteImport.update({
  id: '/rating-speed-run',
  path: '/rating-speed-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentCreatorsRoute = ContentCreatorsRouteImport.update({
  id: '/content-creators',
  path: '/content-creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChessCameroonRoute = ChessCameroonRouteImport.update({
  id: '/chess-cameroon',
  path: '/chess-cameroon',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingSpeedRunIndexRoute = RatingSpeedRunIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RatingSpeedRunRoute,
} as any)
const TournamentsPastOnlineRoute = TournamentsPastOnlineRouteImport.update({
  id: '/tournaments/past-online',
  path: '/tournaments/past-online',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingSpeedRunIdRoute = RatingSpeedRunIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RatingSpeedRunRoute,
} as any)
const ApiSubmitUsernameRoute = ApiSubmitUsernameRouteImport.update({
  id: '/api/submit-username',
  path: '/api/submit-username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitTournamentRoute = ApiSubmitTournamentRouteImport.update({
  id: '/api/submit-tournament',
  path: '/api/submit-tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitCreatorRoute = ApiSubmitCreatorRouteImport.update({
  id: '/api/submit-creator',
  path: '/api/submit-creator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitClubRoute = ApiSubmitClubRouteImport.update({
  id: '/api/submit-club',
  path: '/api/submit-club',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRatingSpeedRunJoinRoute = ApiRatingSpeedRunJoinRouteImport.update({
  id: '/api/rating-speed-run/join',
  path: '/api/rating-speed-run/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRatingSpeedRunCreateRoute = ApiRatingSpeedRunCreateRouteImport.update({
  id: '/api/rating-speed-run/create',
  path: '/api/rating-speed-run/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chess-cameroon': typeof ChessCameroonRoute
  '/clubs': typeof ClubsRoute
  '/content-creators': typeof ContentCreatorsRoute
  '/rating-speed-run': typeof RatingSpeedRunRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/submit-club': typeof ApiSubmitClubRoute
  '/api/submit-creator': typeof ApiSubmitCreatorRoute
  '/api/submit-tournament': typeof ApiSubmitTournamentRoute
  '/api/submit-username': typeof ApiSubmitUsernameRoute
  '/rating-speed-run/$id': typeof RatingSpeedRunIdRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/tournaments/past-online': typeof TournamentsPastOnlineRoute
  '/rating-speed-run/': typeof RatingSpeedRunIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/api/rating-speed-run/create': typeof ApiRatingSpeedRunCreateRoute
  '/api/rating-speed-run/join': typeof ApiRatingSpeedRunJoinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chess-cameroon': typeof ChessCameroonRoute
  '/clubs': typeof ClubsRoute
  '/content-creators': typeof ContentCreatorsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/submit-club': typeof ApiSubmitClubRoute
  '/api/submit-creator': typeof ApiSubmitCreatorRoute
  '/api/submit-tournament': typeof ApiSubmitTournamentRoute
  '/api/submit-username': typeof ApiSubmitUsernameRoute
  '/rating-speed-run/$id': typeof RatingSpeedRunIdRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/tournaments/past-online': typeof TournamentsPastOnlineRoute
  '/rating-speed-run': typeof RatingSpeedRunIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/api/rating-speed-run/create': typeof ApiRatingSpeedRunCreateRoute
  '/api/rating-speed-run/join': typeof ApiRatingSpeedRunJoinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chess-cameroon': typeof ChessCameroonRoute
  '/clubs': typeof ClubsRoute
  '/content-creators': typeof ContentCreatorsRoute
  '/rating-speed-run': typeof RatingSpeedRunRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/submit-club': typeof ApiSubmitClubRoute
  '/api/submit-creator': typeof ApiSubmitCreatorRoute
  '/api/submit-tournament': typeof ApiSubmitTournamentRoute
  '/api/submit-username': typeof ApiSubmitUsernameRoute
  '/rating-speed-run/$id': typeof RatingSpeedRunIdRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/tournaments/past-online': typeof TournamentsPastOnlineRoute
  '/rating-speed-run/': typeof RatingSpeedRunIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/api/rating-speed-run/create': typeof ApiRatingSpeedRunCreateRoute
  '/api/rating-speed-run/join': typeof ApiRatingSpeedRunJoinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chess-cameroon'
    | '/clubs'
    | '/content-creators'
    | '/rating-speed-run'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/submit-club'
    | '/api/submit-creator'
    | '/api/submit-tournament'
    | '/api/submit-username'
    | '/rating-speed-run/$id'
    | '/tournaments/$id'
    | '/tournaments/past-online'
    | '/rating-speed-run/'
    | '/tournaments/'
    | '/api/rating-speed-run/create'
    | '/api/rating-speed-run/join'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chess-cameroon'
    | '/clubs'
    | '/content-creators'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/submit-club'
    | '/api/submit-creator'
    | '/api/submit-tournament'
    | '/api/submit-username'
    | '/rating-speed-run/$id'
    | '/tournaments/$id'
    | '/tournaments/past-online'
    | '/rating-speed-run'
    | '/tournaments'
    | '/api/rating-speed-run/create'
    | '/api/rating-speed-run/join'
  id:
    | '__root__'
    | '/'
    | '/chess-cameroon'
    | '/clubs'
    | '/content-creators'
    | '/rating-speed-run'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/submit-club'
    | '/api/submit-creator'
    | '/api/submit-tournament'
    | '/api/submit-username'
    | '/rating-speed-run/$id'
    | '/tournaments/$id'
    | '/tournaments/past-online'
    | '/rating-speed-run/'
    | '/tournaments/'
    | '/api/rating-speed-run/create'
    | '/api/rating-speed-run/join'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChessCameroonRoute: typeof ChessCameroonRoute
  ClubsRoute: typeof ClubsRoute
  ContentCreatorsRoute: typeof ContentCreatorsRoute
  RatingSpeedRunRoute: typeof RatingSpeedRunRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSubmitClubRoute: typeof ApiSubmitClubRoute
  ApiSubmitCreatorRoute: typeof ApiSubmitCreatorRoute
  ApiSubmitTournamentRoute: typeof ApiSubmitTournamentRoute
  ApiSubmitUsernameRoute: typeof ApiSubmitUsernameRoute
  TournamentsIdRoute: typeof TournamentsIdRoute
  TournamentsPastOnlineRoute: typeof TournamentsPastOnlineRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  ApiRatingSpeedRunCreateRoute: typeof ApiRatingSpeedRunCreateRoute
  ApiRatingSpeedRunJoinRoute: typeof ApiRatingSpeedRunJoinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating-speed-run': {
      id: '/rating-speed-run'
      path: '/rating-speed-run'
      fullPath: '/rating-speed-run'
      preLoaderRoute: typeof RatingSpeedRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-creators': {
      id: '/content-creators'
      path: '/content-creators'
      fullPath: '/content-creators'
      preLoaderRoute: typeof ContentCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chess-cameroon': {
      id: '/chess-cameroon'
      path: '/chess-cameroon'
      fullPath: '/chess-cameroon'
      preLoaderRoute: typeof ChessCameroonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating-speed-run/': {
      id: '/rating-speed-run/'
      path: '/'
      fullPath: '/rating-speed-run/'
      preLoaderRoute: typeof RatingSpeedRunIndexRouteImport
      parentRoute: typeof RatingSpeedRunRoute
    }
    '/tournaments/past-online': {
      id: '/tournaments/past-online'
      path: '/tournaments/past-online'
      fullPath: '/tournaments/past-online'
      preLoaderRoute: typeof TournamentsPastOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id': {
      id: '/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating-speed-run/$id': {
      id: '/rating-speed-run/$id'
      path: '/$id'
      fullPath: '/rating-speed-run/$id'
      preLoaderRoute: typeof RatingSpeedRunIdRouteImport
      parentRoute: typeof RatingSpeedRunRoute
    }
    '/api/submit-username': {
      id: '/api/submit-username'
      path: '/api/submit-username'
      fullPath: '/api/submit-username'
      preLoaderRoute: typeof ApiSubmitUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-tournament': {
      id: '/api/submit-tournament'
      path: '/api/submit-tournament'
      fullPath: '/api/submit-tournament'
      preLoaderRoute: typeof ApiSubmitTournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-creator': {
      id: '/api/submit-creator'
      path: '/api/submit-creator'
      fullPath: '/api/submit-creator'
      preLoaderRoute: typeof ApiSubmitCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-club': {
      id: '/api/submit-club'
      path: '/api/submit-club'
      fullPath: '/api/submit-club'
      preLoaderRoute: typeof ApiSubmitClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rating-speed-run/join': {
      id: '/api/rating-speed-run/join'
      path: '/api/rating-speed-run/join'
      fullPath: '/api/rating-speed-run/join'
      preLoaderRoute: typeof ApiRatingSpeedRunJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rating-speed-run/create': {
      id: '/api/rating-speed-run/create'
      path: '/api/rating-speed-run/create'
      fullPath: '/api/rating-speed-run/create'
      preLoaderRoute: typeof ApiRatingSpeedRunCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RatingSpeedRunRouteChildren {
  RatingSpeedRunIdRoute: typeof RatingSpeedRunIdRoute
  RatingSpeedRunIndexRoute: typeof RatingSpeedRunIndexRoute
}

const RatingSpeedRunRouteChildren: RatingSpeedRunRouteChildren = {
  RatingSpeedRunIdRoute: RatingSpeedRunIdRoute,
  RatingSpeedRunIndexRoute: RatingSpeedRunIndexRoute,
}

const RatingSpeedRunRouteWithChildren = RatingSpeedRunRoute._addFileChildren(
  RatingSpeedRunRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChessCameroonRoute: ChessCameroonRoute,
  ClubsRoute: ClubsRoute,
  ContentCreatorsRoute: ContentCreatorsRoute,
  RatingSpeedRunRoute: RatingSpeedRunRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSubmitClubRoute: ApiSubmitClubRoute,
  ApiSubmitCreatorRoute: ApiSubmitCreatorRoute,
  ApiSubmitTournamentRoute: ApiSubmitTournamentRoute,
  ApiSubmitUsernameRoute: ApiSubmitUsernameRoute,
  TournamentsIdRoute: TournamentsIdRoute,
  TournamentsPastOnlineRoute: TournamentsPastOnlineRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  ApiRatingSpeedRunCreateRoute: ApiRatingSpeedRunCreateRoute,
  ApiRatingSpeedRunJoinRoute: ApiRatingSpeedRunJoinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
